import { redirect } from 'next/navigation'; import Link from 'next/link'; import { getSession } from '@/lib/session'; import { createClient } from '@/lib/supabase/server';
export default async function VisualizarPedidoPainelPage({ searchParams }: { searchParams: Promise<{ [key: string]: string | string[] | undefined }> }) {
  const session = await getSession();
  if (!session || session.nivel !== 2) redirect('/login');
  const params = await searchParams; const id = params.id; if (!id) redirect('/pedidos');
  const supabase = await createClient();
  const { data: pedido } = await (supabase.from('pedidos') as any).select('*, cliente:cliente_id(nome,email,telefone)').eq('id', id).eq('estabelecimento_id', session.estabelecimento_id).single();
  if (!pedido) return <div className="row"><div className="col-md-12"><div className="alert alert-danger">Pedido não encontrado.</div><Link href="/pedidos" className="btn btn-default">Voltar</Link></div></div>;
  const statusLabels: Record<string,string> = { '1': 'Pendente', '2': 'Em Preparação', '3': 'Saiu para Entrega', '4': 'Entregue', '5': 'Cancelado' };
  const statusColors: Record<string,string> = { '1': 'warning', '2': 'info', '3': 'primary', '4': 'success', '5': 'danger' };
  return (<div className="row"><div className="col-md-12"><div className="box box-white"><div className="box-header"><h3 className="box-title">Detalhes do Pedido #{pedido.codigo}</h3></div><div className="box-body"><div className="row"><div className="col-md-6"><h4>Informações do Cliente</h4><p><strong>Nome:</strong> {pedido.cliente?.nome || 'N/A'}</p><p><strong>Email:</strong> {pedido.cliente?.email || 'N/A'}</p><p><strong>Telefone:</strong> {pedido.cliente?.telefone || 'N/A'}</p></div><div className="col-md-6"><h4>Status do Pedido</h4><span className={`label label-${statusColors[pedido.status] || 'default'}`}>{statusLabels[pedido.status] || pedido.status}</span><p style={{ marginTop: '10px' }}><strong>Data:</strong> {new Date(pedido.created).toLocaleString('pt-BR')}</p><p><strong>Total:</strong> R$ {parseFloat(pedido.total).toFixed(2)}</p></div></div><hr /><h4>Itens do Pedido</h4><div className="table-responsive"><table className="table table-striped"><thead><tr><th>Produto</th><th>Qtd</th><th>Preço</th><th>Total</th></tr></thead><tbody><tr><td>{pedido.produto_nome || 'Produto'}</td><td>{pedido.quantidade || 1}</td><td>R$ {parseFloat(pedido.valor || pedido.total).toFixed(2)}</td><td>R$ {parseFloat(pedido.total).toFixed(2)}</td></tr></tbody></table></div><div className="form-group"><Link href="/pedidos" className="btn btn-default">Voltar</Link></div></div></div></div></div>);
}
