import { redirect } from 'next/navigation'; import Link from 'next/link'; import { getSession } from '@/lib/session'; import { createClient } from '@/lib/supabase/server';
export default async function ConfiguracoesPagamentoPage() {
  const session = await getSession();
  if (!session || session.nivel !== 1) redirect('/login');
  const supabase = await createClient();
  const { data: configs } = await (supabase.from('configuracoes') as any).select('*');
  const config = configs?.[0] || {};
  return (<div className="row"><div className="col-md-12"><div className="box box-white"><div className="box-header"><h3 className="box-title">Configurações de Pagamento</h3></div><div className="box-body"><form action="/api/admin/configuracoes/pagamento/salvar" method="POST"><input type="hidden" name="id" value={config.id || ''} /><h4>Mercado Pago</h4><div className="row"><div className="col-md-6"><div className="form-group"><label>Access Token</label><input type="text" name="mp_access_token" className="form-control" defaultValue={config.mp_access_token || ''} /></div></div><div className="col-md-6"><div className="form-group"><label>Public Key</label><input type="text" name="mp_public_key" className="form-control" defaultValue={config.mp_public_key || ''} /></div></div></div><hr /><h4>Stripe</h4><div className="row"><div className="col-md-6"><div className="form-group"><label>Secret Key</label><input type="text" name="stripe_secret_key" className="form-control" defaultValue={config.stripe_secret_key || ''} /></div></div><div className="col-md-6"><div className="form-group"><label>Publishable Key</label><input type="text" name="stripe_publishable_key" className="form-control" defaultValue={config.stripe_publishable_key || ''} /></div></div></div><hr /><h4>PagSeguro</h4><div className="row"><div className="col-md-6"><div className="form-group"><label>Email</label><input type="email" name="pagseguro_email" className="form-control" defaultValue={config.pagseguro_email || ''} /></div></div><div className="col-md-6"><div className="form-group"><label>Token</label><input type="text" name="pagseguro_token" className="form-control" defaultValue={config.pagseguro_token || ''} /></div></div></div><div className="form-group"><button type="submit" className="btn btn-primary"><i className="lni lni-save"></i> Salvar Configurações</button><Link href="/administracao" className="btn btn-default" style={{ marginLeft: '10px' }}>Cancelar</Link></div></form></div></div></div></div>);
}
