import { redirect } from 'next/navigation'; import Link from 'next/link'; import { getSession } from '@/lib/session'; import { createClient } from '@/lib/supabase/server';
export default async function ConfiguracoesGeralPage() {
  const session = await getSession();
  if (!session || session.nivel !== 1) redirect('/login');
  const supabase = await createClient();
  const { data: configs } = await (supabase.from('configuracoes') as any).select('*');
  const config = configs?.[0] || {};
  return (<div className="row"><div className="col-md-12"><div className="box box-white"><div className="box-header"><h3 className="box-title">Configurações Gerais</h3></div><div className="box-body"><form action="/api/admin/configuracoes/salvar" method="POST"><input type="hidden" name="id" value={config.id || ''} /><div className="row"><div className="col-md-6"><div className="form-group"><label>Nome do Site</label><input type="text" name="site_nome" className="form-control" defaultValue={config.site_nome || ''} /></div></div><div className="col-md-6"><div className="form-group"><label>Email de Contato</label><input type="email" name="site_email" className="form-control" defaultValue={config.site_email || ''} /></div></div></div><div className="form-group"><label>Descrição do Site</label><textarea name="site_descricao" className="form-control" rows={3} defaultValue={config.site_descricao || ''}></textarea></div><div className="row"><div className="col-md-6"><div className="form-group"><label>Taxa de Saque (%)</label><input type="number" name="taxa_saque" className="form-control" step="0.01" defaultValue={config.taxa_saque || 0} /></div></div><div className="col-md-6"><div className="form-group"><label>Valor Mínimo de Saque</label><input type="number" name="saque_minimo" className="form-control" step="0.01" defaultValue={config.saque_minimo || 0} /></div></div></div><div className="form-group"><button type="submit" className="btn btn-primary"><i className="lni lni-save"></i> Salvar Configurações</button><Link href="/administracao" className="btn btn-default" style={{ marginLeft: '10px' }}>Cancelar</Link></div></form></div></div></div></div>);
}
