import { redirect } from 'next/navigation'; import Link from 'next/link'; import { getSession } from '@/lib/session'; import { createClient } from '@/lib/supabase/server';
export default async function ConfiguracoesNotificacoesPage() {
  const session = await getSession();
  if (!session || session.nivel !== 1) redirect('/login');
  const supabase = await createClient();
  const { data: configs } = await (supabase.from('configuracoes') as any).select('*');
  const config = configs?.[0] || {};
  return (<div className="row"><div className="col-md-12"><div className="box box-white"><div className="box-header"><h3 className="box-title">Configurações de Notificações</h3></div><div className="box-body"><form action="/api/admin/configuracoes/notificacoes/salvar" method="POST"><input type="hidden" name="id" value={config.id || ''} /><h4>Email</h4><div className="checkbox"><label><input type="checkbox" name="notif_novo_pedido" defaultChecked={config.notif_novo_pedido === 1} /> Notificar novo pedido</label></div><div className="checkbox"><label><input type="checkbox" name="notif_novo_cadastro" defaultChecked={config.notif_novo_cadastro === 1} /> Notificar novo cadastro</label></div><div className="checkbox"><label><input type="checkbox" name="notif_nova_assinatura" defaultChecked={config.notif_nova_assinatura === 1} /> Notificar nova assinatura</label></div><div className="checkbox"><label><input type="checkbox" name="notif_novo_saque" defaultChecked={config.notif_novo_saque === 1} /> Notificar solicitação de saque</label></div><hr /><h4>WhatsApp (API)</h4><div className="row"><div className="col-md-6"><div className="form-group"><label>Token da API</label><input type="text" name="whatsapp_token" className="form-control" defaultValue={config.whatsapp_token || ''} /></div></div><div className="col-md-6"><div className="form-group"><label>Número de Origem</label><input type="text" name="whatsapp_numero" className="form-control" defaultValue={config.whatsapp_numero || ''} placeholder="5511999999999" /></div></div></div><div className="form-group"><button type="submit" className="btn btn-primary"><i className="lni lni-save"></i> Salvar Configurações</button><Link href="/administracao" className="btn btn-default" style={{ marginLeft: '10px' }}>Cancelar</Link></div></form></div></div></div></div>);
}
