import { redirect } from 'next/navigation'; import Link from 'next/link'; import { getSession } from '@/lib/session'; import { createClient } from '@/lib/supabase/server';
export default async function VisualizarProdutoPainelPage({ searchParams }: { searchParams: Promise<{ [key: string]: string | string[] | undefined }> }) {
  const session = await getSession();
  if (!session || session.nivel !== 2) redirect('/login');
  const params = await searchParams; const id = params.id; if (!id) redirect('/produtos');
  const supabase = await createClient();
  const { data: produto } = await (supabase.from('produtos') as any).select('*, categoria:categoria_id(nome)').eq('id', id).eq('estabelecimento_id', session.estabelecimento_id).single();
  if (!produto) return <div className="row"><div className="col-md-12"><div className="alert alert-danger">Produto não encontrado.</div><Link href="/produtos" className="btn btn-default">Voltar</Link></div></div>;
  return (<div className="row"><div className="col-md-12"><div className="box box-white"><div className="box-header"><h3 className="box-title">Detalhes do Produto</h3></div><div className="box-body"><div className="row"><div className="col-md-4">{produto.imagem && (<img src={produto.imagem} alt={produto.nome} style={{ width: '100%', borderRadius: '8px' }} />)}</div><div className="col-md-8"><h3>{produto.nome}</h3><p><strong>Categoria:</strong> {produto.categoria?.nome || 'N/A'}</p><p><strong>Preço:</strong> R$ {parseFloat(produto.preco).toFixed(2)}</p><p><strong>Preço Promocional:</strong> R$ {produto.preco_promocional ? parseFloat(produto.preco_promocional).toFixed(2) : '-'}</p><p><strong>Status:</strong> <span className={`label label-${produto.status === 1 ? 'success' : 'warning'}`}>{produto.status === 1 ? 'Ativo' : 'Inativo'}</span></p><p><strong>Destaque:</strong> <span className={`label label-${produto.destaque === 1 ? 'primary' : 'default'}`}>{produto.destaque === 1 ? 'Sim' : 'Não'}</span></p><hr /><h4>Descrição</h4><p>{produto.descricao || 'Sem descrição'}</p></div></div><div className="form-group" style={{ marginTop: '20px' }}><Link href="/produtos" className="btn btn-default"><i className="lni lni-arrow-left"></i> Voltar</Link><Link href={`/produtos/editar?id=${id}`} className="btn btn-primary" style={{ marginLeft: '10px' }}><i className="lni lni-pencil"></i> Editar</Link></div></div></div></div></div>);
}
