import { redirect } from 'next/navigation'; import Link from 'next/link'; import { getSession } from '@/lib/session'; import { createClient } from '@/lib/supabase/server';
export default async function NotificacoesAdminPage({ searchParams }: { searchParams: Promise<{ [key: string]: string | string[] | undefined }> }) {
  const session = await getSession();
  if (!session || session.nivel !== 1) redirect('/login');
  const params = await searchParams;
  const pagina = parseInt(params.pagina as string) || 1;
  const limite = 20;
  const supabase = await createClient();
  const { data: notificacoes, count } = await (supabase.from('notificacoes') as any).select('*', { count: 'exact' }).eq('usuario_id', session.id).order('created', { ascending: false }).range((pagina - 1) * limite, pagina * limite - 1);
  const totalPaginas = Math.ceil((count || 0) / limite);
  const tipoIcons: Record<string,string> = { 'pedido': 'lni-cart', 'assinatura': 'lni-crown', 'saque': 'lni-wallet', 'sistema': 'lni-cog', 'aviso': 'lni-warning' };
  return (<div className="row"><div className="col-md-12"><div className="box box-white"><div className="box-header"><h3 className="box-title">Notificações</h3><div className="box-tools"><form action="/api/admin/notificacoes/marcar-todas-lidas" method="POST"><button type="submit" className="btn btn-sm btn-default">Marcar todas como lidas</button></form></div></div><div className="box-body"><div className="list-group">{notificacoes && notificacoes.length > 0 ? notificacoes.map((n: any) => (<Link key={n.id} href={n.link || '#'} className={`list-group-item ${n.lida ? '' : 'list-group-item-info'}`}><div className="media"><div className="media-left"><i className={`lni ${tipoIcons[n.tipo] || 'lni-bell'} text-${n.lida ? 'muted' : 'primary'}`} style={{ fontSize: '24px' }}></i></div><div className="media-body"><h4 className="media-heading">{n.titulo} {!n.lida && <span className="label label-primary pull-right">Nova</span>}</h4><p>{n.mensagem}</p><small className="text-muted">{new Date(n.created).toLocaleString('pt-BR')}</small></div></div></Link>)) : (<div className="text-center" style={{ padding: '40px' }}><i className="lni lni-bell" style={{ fontSize: '48px', color: '#ddd' }}></i><p className="text-muted" style={{ marginTop: '10px' }}>Nenhuma notificação</p></div>)}</div><nav className="text-center"><ul className="pagination"><li className={pagina === 1 ? 'disabled' : ''}><Link href={`/administracao/notificacoes?pagina=${pagina - 1}`}>Anterior</Link></li>{Array.from({ length: totalPaginas }, (_, i) => i + 1).map(p => (<li key={p} className={pagina === p ? 'active' : ''}><Link href={`/administracao/notificacoes?pagina=${p}`}>{p}</Link></li>))}<li className={pagina === totalPaginas ? 'disabled' : ''}><Link href={`/administracao/notificacoes?pagina=${pagina + 1}`}>Próxima</Link></li></ul></nav></div></div></div></div>);
}
