import { redirect } from 'next/navigation'; import Link from 'next/link'; import { getSession } from '@/lib/session'; import { createClient } from '@/lib/supabase/server';
export default async function ConfiguracoesEmailPage() {
  const session = await getSession();
  if (!session || session.nivel !== 1) redirect('/login');
  const supabase = await createClient();
  const { data: configs } = await (supabase.from('configuracoes') as any).select('*');
  const config = configs?.[0] || {};
  return (<div className="row"><div className="col-md-12"><div className="box box-white"><div className="box-header"><h3 className="box-title">Configurações de Email</h3></div><div className="box-body"><form action="/api/admin/configuracoes/email/salvar" method="POST"><input type="hidden" name="id" value={config.id || ''} /><div className="row"><div className="col-md-6"><div className="form-group"><label>SMTP Host</label><input type="text" name="smtp_host" className="form-control" defaultValue={config.smtp_host || ''} /></div></div><div className="col-md-3"><div className="form-group"><label>SMTP Porta</label><input type="number" name="smtp_port" className="form-control" defaultValue={config.smtp_port || 587} /></div></div><div className="col-md-3"><div className="form-group"><label>SMTP Segurança</label><select name="smtp_secure" className="form-control" defaultValue={config.smtp_secure || 'tls'}><option value="tls">TLS</option><option value="ssl">SSL</option><option value="none">Nenhuma</option></select></div></div></div><div className="row"><div className="col-md-6"><div className="form-group"><label>SMTP Usuário</label><input type="text" name="smtp_user" className="form-control" defaultValue={config.smtp_user || ''} /></div></div><div className="col-md-6"><div className="form-group"><label>SMTP Senha</label><input type="password" name="smtp_pass" className="form-control" defaultValue={config.smtp_pass || ''} /></div></div></div><div className="row"><div className="col-md-6"><div className="form-group"><label>Email de Envio</label><input type="email" name="email_from" className="form-control" defaultValue={config.email_from || ''} /></div></div><div className="col-md-6"><div className="form-group"><label>Nome de Envio</label><input type="text" name="email_name" className="form-control" defaultValue={config.email_name || ''} /></div></div></div><div className="form-group"><button type="submit" className="btn btn-primary"><i className="lni lni-save"></i> Salvar Configurações</button><Link href="/administracao" className="btn btn-default" style={{ marginLeft: '10px' }}>Cancelar</Link></div></form></div></div></div></div>);
}
