import { redirect } from 'next/navigation'; import Link from 'next/link'; import { getSession } from '@/lib/session'; import { createClient } from '@/lib/supabase/server';
export default async function EditarPerfilPainelPage() {
  const session = await getSession();
  if (!session || session.nivel !== 2) redirect('/login');
  const supabase = await createClient();
  const { data: estabelecimento } = await (supabase.from('estabelecimentos') as any).select('*').eq('id', session.estabelecimento_id).single();
  if (!estabelecimento) return <div className="row"><div className="col-md-12"><div className="alert alert-danger">Estabelecimento não encontrado.</div></div></div>;
  return (<div className="row"><div className="col-md-12"><div className="box box-white"><div className="box-header"><h3 className="box-title">Editar Perfil do Estabelecimento</h3></div><div className="box-body"><form action="/api/painel/perfil/atualizar" method="POST"><input type="hidden" name="id" value={estabelecimento.id} /><div className="row"><div className="col-md-6"><div className="form-group"><label>Nome</label><input type="text" name="nome" className="form-control" defaultValue={estabelecimento.nome} required /></div></div><div className="col-md-6"><div className="form-group"><label>Slug</label><input type="text" name="slug" className="form-control" defaultValue={estabelecimento.slug} required /></div></div></div><div className="row"><div className="col-md-6"><div className="form-group"><label>Email</label><input type="email" name="email" className="form-control" defaultValue={estabelecimento.email} required /></div></div><div className="col-md-6"><div className="form-group"><label>Telefone</label><input type="text" name="telefone" className="form-control" defaultValue={estabelecimento.telefone || ''} /></div></div></div><div className="form-group"><label>Descrição</label><textarea name="descricao" className="form-control" rows={4} defaultValue={estabelecimento.descricao || ''}></textarea></div><div className="form-group"><button type="submit" className="btn btn-primary"><i className="lni lni-save"></i> Salvar Alterações</button><Link href="/perfil" className="btn btn-default" style={{ marginLeft: '10px' }}>Cancelar</Link></div></form></div></div></div></div>);
}
