import { redirect } from 'next/navigation'; import Link from 'next/link'; import { getSession } from '@/lib/session'; import { createClient } from '@/lib/supabase/server';
export default async function PerfilAdminPage() {
  const session = await getSession();
  if (!session || session.nivel !== 1) redirect('/login');
  const supabase = await createClient();
  const { data: usuario } = await (supabase.from('users') as any).select('*').eq('id', session.id).single();
  if (!usuario) return <div className="row"><div className="col-md-12"><div className="alert alert-danger">Usuário não encontrado.</div></div></div>;
  return (<div className="row"><div className="col-md-8 col-md-offset-2"><div className="box box-white"><div className="box-header"><h3 className="box-title">Meu Perfil</h3></div><div className="box-body"><form action="/api/admin/perfil/atualizar" method="POST"><input type="hidden" name="id" value={usuario.id} /><div className="row"><div className="col-md-6"><div className="form-group"><label>Nome</label><input type="text" name="nome" className="form-control" defaultValue={usuario.nome} required /></div></div><div className="col-md-6"><div className="form-group"><label>Email</label><input type="email" name="email" className="form-control" defaultValue={usuario.email} required /></div></div></div><div className="form-group"><label>Telefone</label><input type="text" name="telefone" className="form-control" defaultValue={usuario.telefone || ''} /></div><hr /><h4>Alterar Senha</h4><div className="row"><div className="col-md-6"><div className="form-group"><label>Senha Atual</label><input type="password" name="senha_atual" className="form-control" /></div></div></div><div className="row"><div className="col-md-6"><div className="form-group"><label>Nova Senha</label><input type="password" name="nova_senha" className="form-control" /></div></div><div className="col-md-6"><div className="form-group"><label>Confirmar Nova Senha</label><input type="password" name="confirmar_senha" className="form-control" /></div></div></div><div className="form-group"><button type="submit" className="btn btn-primary"><i className="lni lni-save"></i> Salvar Alterações</button><Link href="/administracao" className="btn btn-default" style={{ marginLeft: '10px' }}>Cancelar</Link></div></form></div></div></div></div>);
}
